[package]
name = "bcr33d_aoc_2024"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.11.1"
maplit = "1.0"

[profile.release]
opt-level = 3
